import {readFile,readdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';import {dirname,resolve,join,relative} from 'node:path';import assert from 'node:assert/strict';
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..');const config=JSON.parse(await readFile(join(app,'site.config.json'),'utf8'));const args=process.argv.slice(2);function option(n,v){const i=args.indexOf(n);return i<0?v:args[i+1];}const website=resolve(app,option('--website',config.websiteRoot)),shared=resolve(app,option('--shared',config.sharedRoot)),output=resolve(website,option('--output',config.outputDirectory));const {readRegistry,landingPath}=await import(pathToFileURL(join(shared,'lib/landing-registry.mjs')));const pages=readRegistry(pathToFileURL(shared+'/')).filter(p=>p.publicationStatus==='approved');const manifest=JSON.parse(await readFile(join(app,'.release/manifest.json'),'utf8'));assert.deepEqual(manifest.pages,pages.map(landingPath));
async function walk(dir){const out=[];for(const e of await readdir(dir,{withFileTypes:true})){if(e.isDirectory())out.push(...await walk(join(dir,e.name)));else if(e.isFile())out.push(join(dir,e.name));}return out;}
const actual=(await walk(output)).map(f=>relative(output,f)).sort();assert.deepEqual(actual,Object.keys(manifest.outputHashes).sort());for(const [file,hash] of Object.entries(manifest.outputHashes))assert.equal(createHash('sha256').update(await readFile(join(output,file))).digest('hex'),hash,file);
for(const [file,hash] of Object.entries(manifest.sourceHashes))assert.equal(createHash('sha256').update(await readFile(join(website,file))).digest('hex'),hash,file);
// Check the image source tree independently of the build manifest: omitted assets
// must fail verification even if the manifest silently excludes them as well.
const originalImages=(await walk(join(website,'images'))).filter(file=>/\.(png|jpe?g|gif|svg|webp|avif|ico)$/i.test(file));
for(const source of originalImages){const file=relative(website,source);assert.ok(actual.includes(file),'Original image missing from release: '+file);assert.equal(createHash('sha256').update(await readFile(join(output,file))).digest('hex'),createHash('sha256').update(await readFile(source)).digest('hex'),'Original image changed: '+file);}
const sitemap=await readFile(join(output,'sitemap.xml'),'utf8'),index=await readFile(join(output,'index.html'),'utf8');for(const p of pages){const path=landingPath(p);assert.ok(sitemap.includes('<loc>'+config.publicOrigin+path+'</loc>'));assert.ok(index.includes('href="'+path+'"'));const html=await readFile(join(output,path.slice(1)+'.html'),'utf8');assert.ok(html.includes('index, follow'));assert.ok(html.includes(config.publicOrigin+path));assert.ok(!html.includes('<form'));if(config.acquisitionEnabled!==true)assert.ok(!/href="[^"]*(?:free-test|signup|apps\.apple\.com|\/api\/)/i.test(html),'Acquisition link on '+path);assert.ok(!html.includes('Private editorial review'));}
// Project-level dashboard rules run before this deployment's routes on every host.
// Check them by invariant (not by count): each recorded rule is well formed, and no
// approved page, vercel.json rewrite/redirect or copied public file is shadowed by one.
const contract=JSON.parse(await readFile(join(shared,'data/funnel-routing-contract.json'),'utf8'));assert.ok(Array.isArray(contract.rules)&&contract.rules.length>0,'Routing contract has no rules');assert.equal(new Set(contract.rules.map(r=>r.id)).size,contract.rules.length,'Duplicate routing rule id');
const ruleRegexes=contract.rules.map(r=>{assert.ok(r.id&&r.match&&r.type,'Malformed routing rule '+JSON.stringify(r));assert.ok(/^https:\/\//.test(r.destination),'Routing rule destination must be absolute https: '+r.id);return {id:r.id,re:new RegExp(r.match)};});
const shadowedBy=path=>ruleRegexes.filter(r=>r.re.test(path)).map(r=>r.id);
for(const p of pages)assert.deepEqual(shadowedBy(landingPath(p)),[],'Approved page shadowed by a project routing rule: '+landingPath(p));
const vercel=JSON.parse(await readFile(join(website,'vercel.json'),'utf8'));assert.equal(vercel.outputDirectory,config.outputDirectory);for(const r of vercel.rewrites||[])assert.ok(pages.some(p=>r.source===landingPath(p)&&r.destination===landingPath(p)+'.html'));assert.equal(vercel.rewrites.length,pages.length);assert.ok(!actual.some(f=>/\.(sql|md|env)$/i.test(f)||f.startsWith('api/')||f.startsWith('seo/')));
for(const r of [...(vercel.rewrites||[]),...(vercel.redirects||[])])assert.deepEqual(shadowedBy(r.source),[],'vercel.json route shadowed by a project routing rule: '+r.source);
for(const f of actual)assert.deepEqual(shadowedBy('/'+f),[],'Public file shadowed by a project routing rule: '+f);
console.log(`PASS release output hashes, clean route allowlist, canonical/indexability/sitemap/navigation, ${contract.rules.length} project routing rules unshadowed (contract version ${contract.versionId}) and isolated internal source (${pages.length} approved pages)`);
