import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {REVIEW_PAGES} from '../lib/review-cohort.ts';import {LandingPageTemplate} from '../components/LandingPageTemplate.tsx';import {ReviewPageTemplate} from '../components/ReviewPageTemplate.tsx';import {safeCampaign,campaignFromSearch,captureCampaign,funnelNavigationUrl,clickRecorder,CAMPAIGN_KEY} from '../lib/funnel-navigation.ts';import {clickAnalyticsPayload} from '../lib/funnel-config.ts';
function memory(initial={}){const m=new Map(Object.entries(initial));return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}
test('single curated registry drives review and public renderer with publication separation',()=>{assert.ok(REVIEW_PAGES.some(p=>p.publicationStatus==='approved'),'at least one approved page');assert.equal(new Set(REVIEW_PAGES.map(p=>p.slug)).size,REVIEW_PAGES.length,'slugs are unique');for(const page of REVIEW_PAGES.filter(p=>p.publicationStatus!=='withdrawn')){const publicHtml=renderToStaticMarkup(React.createElement(LandingPageTemplate,{page,mode:'public'}));const reviewHtml=renderToStaticMarkup(React.createElement(ReviewPageTemplate,{page}));assert.ok(publicHtml.includes(page.title.split(' ')[0]));assert.ok(!/href="[^"]*(?:free-test|signup|apps.apple.com|\/api\/)/.test(publicHtml));assert.ok(publicHtml.includes('Explore the plans'));const enabledHtml=renderToStaticMarkup(React.createElement(LandingPageTemplate,{page,mode:'public',acquisitionEnabled:true}));assert.ok(enabledHtml.includes('https://www.revoapp.ai/free-test'));assert.ok(!publicHtml.includes('<form'));assert.ok(!publicHtml.includes('simulated'));assert.ok(!publicHtml.includes('Preview test flow'));assert.ok(reviewHtml.includes('<form'));assert.ok(reviewHtml.includes('simulated storage'));assert.equal((publicHtml.match(/class="pricing-feature(?: is-off)?"/g)||[]).length,page.pricingVariant==='full'?48:0);}});
test('five-UTM contract preserves encoded values without unknown parameters or identifiable data',()=>{const storage=memory();const u=new URL(funnelNavigationUrl('https://www.revoapp.ai/free-test','?utm_source=google&utm_campaign=Spring%20%26%20Summer&utm_content=HVAC%2BRoofing&utm_term=caf%C3%A9&email=private%40example.invalid&referrer=https%3A%2F%2Fprivate.invalid&gclid=click-id',storage,false));assert.equal(u.searchParams.get('utm_campaign'),'Spring & Summer');assert.equal(u.searchParams.get('utm_content'),'HVAC+Roofing');assert.equal(u.searchParams.get('utm_term'),'café');assert.deepEqual([...u.searchParams.keys()],['utm_source','utm_campaign','utm_content','utm_term']);assert.equal(storage.getItem(CAMPAIGN_KEY),null);assert.deepEqual(campaignFromSearch('?utm_source=first&utm_source=second'),{});assert.deepEqual(safeCampaign({utm_source:'private@example.invalid',utm_medium:'5551234567',utm_term:'https://private.invalid',utm_content:'ok\nno'}),{});assert.throws(()=>funnelNavigationUrl('https://other.invalid/free-test','',storage,true));});
test('consent controls campaign session storage; fresh campaign replaces prior and denial clears it',()=>{const storage=memory();assert.deepEqual(captureCampaign('?utm_source=google',storage,true),{utm_source:'google'});assert.deepEqual(captureCampaign('',storage,true),{utm_source:'google'});assert.deepEqual(captureCampaign('?utm_campaign=next',storage,true),{utm_campaign:'next'});assert.deepEqual(captureCampaign('',storage,false),{});assert.equal(storage.getItem(CAMPAIGN_KEY),null);assert.equal(funnelNavigationUrl('https://www.revoapp.ai/free-test','',memory(),false),'https://www.revoapp.ai/free-test');});
test('one click event is deduplicated and analytics context excludes query, campaign, referrer and PII',()=>{const sent=[];const record=clickRecorder((...args)=>sent.push(args));const e={};const payload=clickAnalyticsPayload('https://www.revoapp.ai/ai-answering-service/after-hours?email=private@example.invalid&utm_campaign=John#phone','hero','https://www.revoapp.ai/free-test?utm_campaign=John');assert.equal(record(e,'page:hero',payload,0),true);assert.equal(record(e,'page:hero',payload,900),false);assert.equal(record({},'page:hero',payload,100),false);assert.equal(record({},'page:hero',payload,901),true);assert.equal(sent.length,2);assert.equal(payload.page_referrer,'');assert.equal(payload.page_location,'https://www.revoapp.ai/ai-answering-service/after-hours');assert.deepEqual(Object.keys(payload).sort(),['cta_placement','destination_path','landing_page','page_location','page_referrer']);assert.ok(!JSON.stringify(sent).includes('private'));assert.ok(!JSON.stringify(sent).includes('utm'));});
test('public chrome defaults to editorial navigation and explicit enable restores acquisition',async()=>{const {RevoBrandHeader,RevoBrandFooter}=await import('../components/RevoBrandChrome.tsx');for(const Component of [RevoBrandHeader,RevoBrandFooter]){const html=renderToStaticMarkup(React.createElement(Component,{mode:'public'}));assert.ok(!/href="[^"]*(?:free-test|signup|apps\.apple\.com|\/api\/)/i.test(html));assert.ok(html.includes('/ai-answering-service/'));}const enabled=renderToStaticMarkup(React.createElement(RevoBrandHeader,{mode:'public',acquisitionEnabled:true}));assert.ok(enabled.includes('https://www.revoapp.ai/free-test'));assert.ok(enabled.includes('https://apps.apple.com/'));});

test('guide header keeps original industry destinations and removes content-only header CTAs',async()=>{
 const {RevoBrandHeader,RevoBrandFooter}=await import('../components/RevoBrandChrome.tsx');
 const {readFileSync}=await import('node:fs');
 const source=readFileSync(new URL('../../../index.html',import.meta.url),'utf8');
 const menu=source.slice(source.indexOf('<div class="megamenu">'),source.indexOf('<!-- Right Section - Actions -->'));
 const expected=[...menu.matchAll(/href="(industry_[^"]+\.html)"/g)].map(m=>'/'+m[1]).sort();
 const header=renderToStaticMarkup(React.createElement(RevoBrandHeader,{mode:'public',acquisitionEnabled:false}));
 const actual=[...header.matchAll(/href="(\/industry_[^"]+\.html)"/g)].map(m=>m[1]).sort();
 assert.deepEqual(actual,expected);
 assert.ok(header.includes('<summary>Industry'));
 assert.ok(!/Read call guides|Explore the worksheet|Get Started|Download for iPhone|free-test|apps\.apple\.com/.test(header));
 assert.ok(!renderToStaticMarkup(React.createElement(RevoBrandFooter,{mode:'public'})).includes('Call planning'));
});

test('keyword headings render exactly and calculator starts without invented inputs',()=>{
 for(const page of REVIEW_PAGES){const html=renderToStaticMarkup(React.createElement(LandingPageTemplate,{page,mode:'public'}));const heading=html.match(/<h1>(.*?)<\/h1>/s)[1].replace(/<[^>]*>/g,'');assert.equal(heading,page.h1??page.title);}
 const calculator=REVIEW_PAGES.find(page=>page.calculator);
 const html=renderToStaticMarkup(React.createElement(LandingPageTemplate,{page:calculator,mode:'public'}));
 assert.equal((html.match(/<input[^>]*value=""/g)||[]).length,4);
 assert.ok(html.includes('No costs are subtracted'));
 assert.ok(html.includes('does not assume repeat business or annualize'));
});
