"use client";
import {useState} from "react";
import {scenarioValue} from "@/lib/review-cohort";
export function ReviewScenarioCalculator() {
 const [period,setPeriod]=useState("");const [inquiries,setInquiries]=useState("");const [probability,setProbability]=useState("");const [value,setValue]=useState("");
 let result:number|null=null;let error="";
 if(period.trim() && inquiries!=="" && probability!=="" && value!=="") {try {result=scenarioValue(Number(inquiries),Number(probability),Number(value));}catch {error="Use a whole number of inquiries, a probability from 0 to 100 and a non-negative job value.";}}
 return <div className="revo-scenario"><h2>Missed call calculator: your scenario</h2><p>All inputs start blank. Use one defined period and your own records or clearly stated assumptions.</p><div className="revo-scenario-workspace"><div className="revo-inputs"><label>Period covered<input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="Your chosen period" /></label><label>Unanswered qualified inquiries<input type="number" min="0" step="1" value={inquiries} onChange={e=>setInquiries(e.target.value)} /></label><label>Assumed booking probability (%)<input type="number" min="0" max="100" step="any" value={probability} onChange={e=>setProbability(e.target.value)} /></label><label>Assumed average gross job value (USD)<input type="number" min="0" step="any" value={value} onChange={e=>setValue(e.target.value)} /></label></div><output aria-live="polite">{error || (result===null ? "Enter all four inputs to explore a scenario." : `Potential gross job value for ${period}: ${new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(result)}`)}</output></div><p>Formula: qualified inquiries × assumed booking probability ÷ 100 × assumed gross job value. No costs are subtracted. This is hypothetical potential value for your chosen period, not measured lost revenue, savings, profit or ROI. It does not assume repeat business or annualize the result.</p></div>;
}
